# Generated by Django 4.2 on 2023-04-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartprocessorders',
            name='id_cart',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartprocessorders',
            name='id_nub_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
